# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91f6a6df02af461fa2df7c291e1e52f72ee64b90fb32548102cf7fb6b8ddc55c32e6a8f1c5aa0501003e3edf583aec2858830883174572d702d186041d3802a2

test:
  secret_key_base: 76c50ed293044e03cc456fbe98f8bd629016c416e4f80c0164b3ca5febe0594576e19c5e9bf9a260dd9efb0f78ca6301121c7e6b84944b436c77da790d6f7932

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
